task:
  name: Build OrangeFox X6512 (boot.img)
  container:
    image: ubuntu:18.04
    cpu: 8
    memory: 32G
  environment:
    MANIFEST_BRANCH: fox_11.0
    DEVICE_TREE: https://github.com/manusia251/twrp-test.git
    DEVICE_BRANCH: main
    DEVICE_CODENAME: X6512
    TARGET_RECOVERY_IMAGE: boot
    DEBIAN_FRONTEND: noninteractive
  install_script:
    # Update package lists
    - apt-get update
    
    # Install official AOSP dependencies for Ubuntu 18.04+
    - apt-get install -y \
      git-core gnupg flex bison build-essential zip curl zlib1g-dev \
      libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev \
      libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
      
    # Install additional packages needed for recovery building
    - apt-get install -y \
      openjdk-8-jdk gcc-multilib g++-multilib lib32ncurses5-dev \
      libncurses5-dev gperf ccache lzop pngcrush schedtool \
      python python3 rsync bc libssl-dev
      
    # Install useful tools
    - apt-get install -y \
      wget ca-certificates nano vim screen
      
  script:
    # Configure git
    - git config --global user.name "manusia251"
    - git config --global user.email "darkside@gmail.com"
    
    # Set up build environment
    - export USE_CCACHE=1
    - export CCACHE_COMPRESS=1
    - export CCACHE_DIR="/tmp/ccache"
    - export CCACHE_MAX_SIZE=50G
    
    # Clone builder repository
    - echo "Cloning builder repository..."
    - git clone https://github.com/manusia251/Lazy_Action-Recoverys-Builder builder
    - cd builder
    
    # List files to debug
    - echo "Files in builder directory:"
    - ls -la
    
    # Check if build script exists and make it executable
    - if [ -f build-ofrp.sh ]; then chmod +x build-ofrp.sh; else echo "build-ofrp.sh not found!"; exit 1; fi
    
    # Show environment variables
    - echo "Environment variables:"
    - echo "DEVICE_TREE: $DEVICE_TREE"
    - echo "DEVICE_BRANCH: $DEVICE_BRANCH" 
    - echo "DEVICE_CODENAME: $DEVICE_CODENAME"
    - echo "MANIFEST_BRANCH: $MANIFEST_BRANCH"
    - echo "TARGET_RECOVERY_IMAGE: $TARGET_RECOVERY_IMAGE"
    
    # Build OrangeFox Recovery
    - echo "Starting OrangeFox build..."
    - bash build-ofrp.sh "$DEVICE_TREE" "$DEVICE_BRANCH" "$DEVICE_CODENAME" "$MANIFEST_BRANCH" "$TARGET_RECOVERY_IMAGE"
    
  artifacts:
    path: builder/output/**/*
  timeout_in: 120m
