task:
  name: Build OrangeFox X6512 (boot.img)
  container:
    image: ubuntu:18.04
    cpu: 8
    memory: 32G
  environment:
    MANIFEST_BRANCH: fox_11.0
    DEVICE_TREE: https://github.com/manusia251/twrp-test.git
    DEVICE_BRANCH: main
    DEVICE_CODENAME: X6512
    TARGET_RECOVERY_IMAGE: boot
    DEBIAN_FRONTEND: noninteractive
  install_script:
    # Update package lists
    - apt-get update
    
    # Install build dependencies - Ubuntu 18.04 compatible
    - apt-get install -y \
      bc bison build-essential curl flex g++-multilib gcc-multilib \
      git gnupg gperf lib32ncurses5-dev lib32z1-dev libncurses5-dev \
      libncurses5 libncurses-dev libsdl1.2-dev libssl-dev libxml2 \
      libxml2-utils lzop openjdk-8-jdk pngcrush schedtool \
      squashfs-tools xsltproc zip zlib1g-dev python python3 \
      unzip fontconfig ccache rsync
      
    # Install additional useful packages
    - apt-get install -y \
      wget ca-certificates nano vim
      
  script:
    # Configure git
    - git config --global user.name "manusia251"
    - git config --global user.email "darkside@gmail.com"
    
    # Set up build environment
    - export USE_CCACHE=1
    - export CCACHE_COMPRESS=1
    - export CCACHE_DIR="/tmp/ccache"
    - export CCACHE_MAX_SIZE=50G
    
    # Clone builder repository
    - echo "Cloning builder repository..."
    - git clone https://github.com/manusia251/Lazy_Action-Recoverys-Builder builder
    - cd builder
    
    # List files to debug
    - echo "Files in builder directory:"
    - ls -la
    
    # Check if build script exists and make it executable
    - if [ -f build-ofrp.sh ]; then chmod +x build-ofrp.sh; else echo "build-ofrp.sh not found!"; exit 1; fi
    
    # Show environment variables
    - echo "Environment variables:"
    - echo "DEVICE_TREE: $DEVICE_TREE"
    - echo "DEVICE_BRANCH: $DEVICE_BRANCH" 
    - echo "DEVICE_CODENAME: $DEVICE_CODENAME"
    - echo "MANIFEST_BRANCH: $MANIFEST_BRANCH"
    - echo "TARGET_RECOVERY_IMAGE: $TARGET_RECOVERY_IMAGE"
    
    # Build OrangeFox Recovery
    - echo "Starting OrangeFox build..."
    - bash build-ofrp.sh "$DEVICE_TREE" "$DEVICE_BRANCH" "$DEVICE_CODENAME" "$MANIFEST_BRANCH" "$TARGET_RECOVERY_IMAGE"
    
  artifacts:
    path: builder/output/**/*
  timeout_in: 120m
